<?php

namespace Ezsc\WorkshopBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function findTasks($taskListId, $order = null)
    {
        $qb = $this->createQueryBuilder('t');
        $qb
                ->select()
                ->where('t.taskList = :taskListId')
                ->setParameter('taskListId', $taskListId);
        if($order == 'DESC')
            $qb->orderBy ('t.dateDeadlineAt','DESC');
        else
            $qb->orderBy ('t.dateDeadlineAt','ASC');
        
        return $qb->getQuery()->getResult();
    }
}
